Relocated distributor logos
keeferrourke/la-capitaine-icon-theme pull request #574
Opened 2020-10-05 20:00 UTC by stefanobartoletti

Moved distributor logos from from `apps` to `places`, fixes #570 
Also cleaned their code a bit in the process.

2020-10-12 02:34 UTC, keeferrourke requested changes
LGTM, except for the icons I pointed out that seem to have been randomly resized.

Also note that `distributor-logo.svg` was a symlink to `distributor-logo-gnome.svg` prior to this change-set. In this PR, it's a copy of the Ubuntu distributor logo. I bet your local configuration overwrote this, so can you please revert that file?

2020-10-12 02:34 UTC, keeferrourke commented on places/scalable/distributor-logo-archlinux.svg
> +  <path d="m673.99096 786.06661c-1.20204 2.94701-1.92701 4.87468-3.26527 7.73381.82049.86979 1.82767 1.88264 3.46336 3.02662-1.75849-.72364-2.95796-1.4501-3.85435-2.20396-1.71272 3.57396-4.39615 8.66
Am I crazy, or has the icon size been increased here? The rich diff seems to show a lack of padding between the image border and the icon.

... If I'm not crazy, please resize this icon back as it was before.

2020-10-12 02:34 UTC, keeferrourke commented on places/scalable/distributor-logo-archlinux.svg
> +  <path d="m673.99096 786.06661c-1.20204 2.94701-1.92701 4.87468-3.26527 7.73381.82049.86979 1.82767 1.88264 3.46336 3.02662-1.75849-.72364-2.95796-1.4501-3.85435-2.20396-1.71272 3.57396-4.39615 8.66
Okay I'm not crazy! This also happened for the Debian, Fedora, Gentoo, Mageia, Manjaro, OpenSUSE, Rosa, and Ubuntu distributor logos.

2020-10-15 19:58 UTC, stefanobartoletti commented
Sorry for the mess, the script that I use to clean svg files has probably taken way too much files.
I'll fix this.

2020-10-15 20:27 UTC, stefanobartoletti commented
Ok, I did a quick research, some icons were present both on `apps` and on `places`, so when I move them these were overwritten. 
Anyway, the difference on the size of many of these distributor logos icons is something already present in the master branch, (maybe because these were done in different times by different persons?).

As an example, the Arch Linux icon is present in both directories, with the icon itself being 48px in one and 44px in another (the canvas size is 48px for both). 

I'm pretty sure that there are also various other circular app icons that are 46px wide.

I'm not really sure which size is supposed to be the standard. What's the correct way here?

2020-10-18 20:58 UTC, keeferrourke commented
I think we want to standardize on a 44px icon centered on a 48px canvas.

2020-10-28 22:18 UTC, stefanobartoletti commented
I've resized all these icons to be 44x44 inside a 48x48 canvas.

Now they should all adhere to the standard.

Please let me know if this fixes the issue.

2020-11-01 18:11 UTC, keeferrourke approved these changes
LGTM!

2020-11-01 18:11 UTC, merged