Lutris
keeferrourke/la-capitaine-icon-theme pull request #575
Opened 2020-10-05 20:05 UTC by stefanobartoletti

Redone Lutris icon.

It is a modified version of the official logo (I like to stick to brand icons when possible), with smoother gradients to give it the "capitaine" look.
There is also a symlink for the Flatpak version.

It is pretty different from the icon already present in the theme, feel free to reject it if you don't like it.

2020-10-10 12:11 UTC, keeferrourke commented
No complaints from me about this icon, my only concern is that the official brand icon doesn't make it clear that Lutris is a gaming platform (of course, very few brand icons have a clear meaningful representation).

I'd like to merge this, but maybe keep the old icon as `lutris-alt`?

2020-10-12 02:36 UTC, keeferrourke requested changes
Let's rename the old lutrix icon to `lutris-alt.svg`, rather than delete it.

2020-10-15 19:55 UTC, stefanobartoletti commented
Thank you. Here it is, this should do.

2020-10-18 20:56 UTC, keeferrourke approved these changes

2020-10-18 20:57 UTC, merged